### ISSUE TITLE
fedora25打包出现问题

### ISSUE THREAD

**Issue by ArchonMeng** [chitosai/bilimini#19]
npm start可以运行
但是npm run dist时出现问题
[npm-debug.txt](https://github.com/chitosai/bilimini/files/1082630/npm-debug.txt)

linux新人，多多指教

**Comment by chitosai** [comment]
不是很看得懂发生了什么，试试看运行`node_modules/.bin/build --linux`？

**Comment by ArchonMeng** [comment]
好像是图标打包的问题
Building AppImage for arch x64
Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/commadama/文档/bilimini-master/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:211:5)
    at ChildProcess.errorhandler (child_process.js:223:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (/home/commadama/文档/bilimini-master/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/commadama/文档/bilimini-master/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:170:28
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:

**Comment by chitosai** [comment]
你试一下在build目录下建一个icons文件夹，然后把icon.png改名为icon_60x60.png丢进新建的icons目录，然后再运行一次打包试试？
